name: Business API CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "legal-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./legal-api

jobs:
  business-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/api-ci.yaml@main
    with:
      app_name: "business-api"
      working_directory: "./business-api"
      codecov_flag: "legalapi"