name: Business Future Effective Filings Job CD

on:
  push:
    branches:
      - main
    paths:
      - "./jobs/future-effective-filings/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod

jobs:
  business-future-effective-filings-cd:
    uses: pwei1018/bcregistry-sre/.github/workflows/cloud-run-job-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "business-future-effective-filings"
      working_directory: "./jobs/future-effective-filings"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
